debug: false
database:
  use-mysql: false
  mysql:
    host: localhost
    port: 3306
    database: apartmentcore
    username: root
    password: password
    pool-size: 10
    connection-timeout: 5000
economy:
  currency-symbol: $
  default-price: 10000
  default-tax: 500
  default-tax-days: 7
  sell-percentage: 70
  penalty-percentage: 25
  income-interval: 3600
  tax-interval: 86400
guestbook:
  max-messages: 50
apartment-levels:
  level-1:
    min-income: 10
    max-income: 100
    upgrade-cost: 0
  level-2:
    min-income: 100
    max-income: 200
    upgrade-cost: 1000
  level-3:
    min-income: 200
    max-income: 300
    upgrade-cost: 2000
  level-4:
    min-income: 300
    max-income: 400
    upgrade-cost: 3000
  level-5:
    min-income: 400
    max-income: 500
    upgrade-cost: 5000
time:
  ticks-per-hour: 1000
  ticks-per-day: 24000
  inactive-grace-period: 3
auto-save:
  enabled: true
  interval-minutes: 10
performance:
  use-async: true
  use-cache: true
  cache-expiry: 300
messages:
  prefix: '&6[ApartmentCore] &r'
  use-colors: true
  language: en_US
limits:
  max-apartments-per-player: 5
  max-apartment-price: 1000000
  min-apartment-price: 100
  max-tax-amount: 100000
  min-tax-amount: 10
worldguard:
  auto-add-owner: true
  auto-remove-owner: true
  check-flags: true
  required-flags:
    - 'build: deny'
    - 'pvp: deny'
placeholderapi:
  enabled: true
  update-interval: 60
logging:
  log-transactions: true
  log-admin-actions: true
  log-file: logs/apartmentcore.log
  max-log-size: 10
  keep-old-logs: true
  max-old-logs: 10
security:
  require-confirmation: true
  confirmation-timeout: 30
  log-suspicious: true
  command-cooldown: 1000
messages-text:
  no-permission: '&cYou don''t have permission to use this command!'
  apartment-not-found: '&cApartment not found!'
  not-enough-money: '&cYou don''t have enough money!'
  apartment-bought: '&aSuccessfully purchased apartment {id} for {price}!'
  apartment-sold: '&aSuccessfully sold apartment {id} for {price}!'
  tax-paid: '&aTax paid successfully!'
  income-claimed: '&aClaimed {amount} from your apartment!'
  apartment-created: '&aApartment {id} created successfully!'
  apartment-removed: '&aApartment {id} removed successfully!'
  config-reloaded: '&aConfiguration reloaded successfully!'
  player-not-found: '&cPlayer not found!'
  already-owned: '&cThis apartment is already owned!'
  not-owner: '&cYou don''t own this apartment!'
  invalid-arguments: '&cInvalid arguments! Use /apartmentcore help'
  teleport-success: '&aTeleported to apartment {id}!'
  no-income: '&cNo income to claim!'
  apartment-inactive: '&cThis apartment is inactive due to unpaid taxes!'
  penalty-warning: '&eYou have a penalty of {amount} for late tax payment!'
features:
  income-generation: true
  tax-system: true
  level-system: true
  teleportation: true
  player-trading: false
  auctions: false
config-version: 1
placeholders:
  apartment_last_rent_claim: Shows last time rent was claimed
  apartment_next_income_time: Shows countdown to next passive income
  apartment_next_tax_time: Shows countdown to next tax
  apartment_stats: Shows detailed apartment statistics
  apartment_guestbook_latest: Shows latest guestbook message
  apartment_tour_location: Preview location for apartment tours
teleport:
  default-location: world,0,64,0
